name: Nightly Build and Deploy

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Every night at midnight UTC
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workflow repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            workspace/gradle
            workspace/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('workspace/**/*.gradle*', 'workspace/gradle-wrapper.properties', 'workspace/gradle/**', 'workspace/gradle.properties') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x workspace/gradlew


      - name: Build all (makeMainOfflineDownload & makeMainWasmClientBundle)
        working-directory: workspace
        run: ./gradlew makeMainOfflineDownload makeMainWasmClientBundle --parallel

      - name: Add version and timestamp to build files
        working-directory: workspace
        run: |
          TS=$(date +%m%d%Y)
          VER=$(cat desktopRuntime/resources/EPKVersionIdentifier.txt | tr -d '\n' | tr -d '\r')
          for f in target_teavm_javascript/javascript/*.html; do [ -e "$f" ] && mv "$f" "${f%.html}-$VER-$TS.html" || true; done
          for f in target_teavm_wasm_gc/javascript_dist/*.html; do [ -e "$f" ] && mv "$f" "${f%.html}-$VER-$TS.html" || true; done

      - name: Delete all assets from Nightly Release before upload
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: nightly
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or Update Nightly Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: Nightly Build
          files: |
            workspace/target_teavm_javascript/javascript/EaglercraftX_1.8_Offline_en_US-*.html
            workspace/target_teavm_javascript/javascript/EaglercraftX_1.8_Offline_International-*.html
            workspace/target_teavm_wasm_gc/javascript_dist/EaglercraftX_1.8_WASM-GC_Offline_Download-*.html
          prerelease: true
          draft: false
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare GitHub Pages content
        run: |
          mkdir -p gh-pages-publish/js gh-pages-publish/wasm
          rm -rf gh-pages-publish/js/* gh-pages-publish/wasm/*
          cp -r workspace/target_teavm_javascript/javascript/* gh-pages-publish/js/
          cp -r workspace/target_teavm_wasm_gc/javascript_dist/* gh-pages-publish/wasm/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages-publish