name: Nightly Build and Deploy

on:
  #schedule:
   # - cron: '0 0 * * *' # Every night at midnight UTC
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workflow repository (no submodules)
        uses: actions/checkout@v4

      - name: Init submodules with fallback
        run: |
          set -e
          git submodule update --init --recursive --remote || (
            git config submodule.workspace.url https://github.com/Eaglercraft-Archive/EaglercraftX-1.8-workspace.git
            git submodule sync
            git submodule update --init --recursive --remote
          )

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            workspace/gradle
            workspace/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('workspace/**/*.gradle*', 'workspace/gradle-wrapper.properties', 'workspace/gradle/**', 'workspace/gradle.properties') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x workspace/gradlew


      - name: Build all (makeMainOfflineDownload & makeMainWasmClientBundle)
        working-directory: workspace
        run: ./gradlew makeMainOfflineDownload makeMainWasmClientBundle --parallel

      - name: Delete nightly release and tag before upload
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: nightly
          delete_release: true
          delete_tag: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or Update Nightly Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: Nightly Build
          files: |
            workspace/target_teavm_javascript/javascript/EaglercraftX_1.8_Offline_en_US.html
            workspace/target_teavm_javascript/javascript/EaglercraftX_1.8_Offline_International.html
            workspace/target_teavm_wasm_gc/javascript_dist/EaglercraftX_1.8_WASM-GC_Offline_Download.html
          prerelease: true
          draft: false
          overwrite: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare GitHub Pages content
        run: |
          mkdir -p gh-pages-publish/js gh-pages-publish/wasm
          rm -rf gh-pages-publish/js/* gh-pages-publish/wasm/*
          cp -r workspace/target_teavm_javascript/javascript/* gh-pages-publish/js/
          cp -r workspace/target_teavm_wasm_gc/javascript_dist/* gh-pages-publish/wasm/
          # Append version info to the index.html page
          if [ -f gh-pages-publish/index.html ] && [ -f workspace/desktopRuntime/resources/EPKVersionIdentifier.txt ]; then \
            VER=$(cat workspace/desktopRuntime/resources/EPKVersionIdentifier.txt | tr -d '\n' | tr -d '\r'); \
            echo "<div style=\"position:absolute;top:0;right:0;background:#eee;padding:4px;font-size:small;z-index:9999;\">EaglercraftX Version: $VER</div>" >> gh-pages-publish/index.html; \
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages-publish
